AWS_ACCESS_KEY_ID = "AKIAV7SWZG7BKMK4TAGG"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"
EMAIL = "NICOLEMARK@GMAIL.COM"
PASSWORD = "Marimekkok810#"