AWS_ACCESS_KEY_ID = "AKIAV7SWZG7BKMK4TAGG"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"
REPLICATE_API_TOKEN = "r8_FgoCe8S7E2efNmE2QwqjSR4ZdtAI86w2VYezo"